version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: nestjs-folders-postgres
    environment:
      POSTGRES_DB: nestjsfoldersdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nestjs-folders-network

  redis:
    image: redis:6.2
    container_name: nestjs-folders-redis
    ports:
      - '6379:6379'
    networks:
      - nestjs-folders-network

volumes:
  postgres_data:

networks:
  nestjs-folders-network:
    driver: bridge
